meta_product_name: "Web Glossary"
meta_title: "Web development - Glossary"
meta_description: "This website help me to remember some useful web developpement keywords"
meta_image: "android-icon-192x192.png" # Une image dans votre dossier app/assets/images/
